import type { NextPage } from 'next'
import Head from 'next/head'
import { Sidebar, Trade } from 'components'
import { useAppState } from 'lib/overmind'

const Home: NextPage = () => {
  const { appLoading } = useAppState()
  if (appLoading) {
    console.log('app is loading')
    return <div>loading...</div>
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='min-h-screen bg-base grid grid-cols-8 font-Josefin'>
        <Sidebar />
        <Trade />
      </main>
    </>
  )
}

export default Home
