import type { NextPage } from 'next'
import Head from 'next/head'
import { Sidebar, Trade } from 'components'
import { useStore } from 'lib/zustand'
import { useEffect } from 'react'

const Home: NextPage = () => {
  const [appLoading, fetchInitialAssetPrices] = useStore((state) => [
    state.appLoading,
    state.fetchInitialAssetPrices,
  ])

  useEffect(() => {
    if (appLoading) {
      fetchInitialAssetPrices()
    }
  }, [appLoading, fetchInitialAssetPrices])

  return (
    <>
      <Head>
        <title>My Google Wallet</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <main className='h-[92vh] bg-base grid grid-cols-8 font-Josefin'>
        <Sidebar />
        <Trade />
      </main>
    </>
  )
}

export default Home
